# Generated by Django 4.2.2 on 2023-10-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_dev2",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
